name : Continuous Integration

on: 
  pull_request:
    paths:
      - 'backend/**'
  push:
    paths:
      - 'backend/**'

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change to backend folder
        run: cd backend

      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.

      - name: Run install dependencies and test 
        run:
          npm install
          npx jest tests